#!/usr/bin/env python

import os

env = SConscript("../.tools/godot-cpp/SConstruct")
env.Append(CPPPATH=["../libphyz/include", "src"])
if env.get("is_msvc", False):
    env.Append(CXXFLAGS=["/std:c++20", "/O2", "/W4"])
else:
    env.Append(CXXFLAGS=["-std=c++20", "-O2", "-Wall", "-Wextra", "-Wpedantic"])

sources = Glob("src/*.cpp") + Glob("../libphyz/src/*.cpp")
library = env.SharedLibrary(
    "bin/libphyzbox{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
    source=sources,
)
Default(library)
